name:                ddd-machines
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/ddd-machines#readme
license:             OtherLicense
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2021 Marco Perone
category:            Web
extra-source-files:
- README.md

ghc-options:
  -W
  -Wall
  -Werror
  -fwrite-ide-info
  -hiedir=.hie

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:       src
  dependencies:
    - profunctors

executables:
  ddd-machines:
    source-dirs:     app
    main:            Main.hs
    dependencies:
      - ddd-machines

tests:
  ddd-machines-spec:
    main:             Spec.hs
    source-dirs:      spec
    dependencies:
      - ddd-machines
      - hspec
      - profunctors
      - QuickCheck
